## Open3D点群とNumPy行列の相互変換

In [1]:
import numpy as np
from open3d import *

### 10x3のNumPy行列の生成（値はランダム）

In [6]:
data = np.random.rand(10,3)

In [18]:
print(data)

[[ 0.09249111  0.57397975  0.55690015]
 [ 0.50281529  0.09562299  0.24029229]
 [ 0.28317499  0.75393479  0.72160014]
 [ 0.96927297  0.08838792  0.1848289 ]
 [ 0.60801702  0.95011524  0.9681312 ]
 [ 0.40435173  0.11033132  0.93538947]
 [ 0.08502744  0.85777887  0.36894673]
 [ 0.9156053   0.40921759  0.69935851]
 [ 0.47280768  0.43104577  0.90596331]
 [ 0.99682753  0.67177541  0.26291334]]


### NumPy行列をOpen3D点群に変換

In [10]:
pcd = PointCloud()
pcd.points = Vector3dVector(data)

### 点群に色を設定する（値の範囲は[0,1]）

In [13]:
pcd.paint_uniform_color([1, 0.706, 0])

### 点群の概要の表示（1行目）と実際のデータの表示（2,3行目）

In [14]:
print(pcd)
print(np.asarray(pcd.points))
print(np.asarray(pcd.colors))

PointCloud with 10 points.
[[ 0.09249111  0.57397975  0.55690015]
 [ 0.50281529  0.09562299  0.24029229]
 [ 0.28317499  0.75393479  0.72160014]
 [ 0.96927297  0.08838792  0.1848289 ]
 [ 0.60801702  0.95011524  0.9681312 ]
 [ 0.40435173  0.11033132  0.93538947]
 [ 0.08502744  0.85777887  0.36894673]
 [ 0.9156053   0.40921759  0.69935851]
 [ 0.47280768  0.43104577  0.90596331]
 [ 0.99682753  0.67177541  0.26291334]]
[[ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]]


### Open3D点群をNumPy行列に変換

In [15]:
xyz = np.asarray(pcd.points)
color = np.asarray(pcd.colors)

In [16]:
print(xyz)
print(color)

[[ 0.09249111  0.57397975  0.55690015]
 [ 0.50281529  0.09562299  0.24029229]
 [ 0.28317499  0.75393479  0.72160014]
 [ 0.96927297  0.08838792  0.1848289 ]
 [ 0.60801702  0.95011524  0.9681312 ]
 [ 0.40435173  0.11033132  0.93538947]
 [ 0.08502744  0.85777887  0.36894673]
 [ 0.9156053   0.40921759  0.69935851]
 [ 0.47280768  0.43104577  0.90596331]
 [ 0.99682753  0.67177541  0.26291334]]
[[ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]
 [ 1.     0.706  0.   ]]


### 点群のレンダリング

In [17]:
draw_geometries([pcd])